-- ============================================================
-- SAMA ÉCONOMIE — NETTOYAGE NUCLÉAIRE
-- Exécuter CELUI-CI en premier dans Supabase SQL Editor
-- Utilise DO $$ pour ignorer les erreurs si une table n'existe pas
-- ============================================================

DO $$ BEGIN
  DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
EXCEPTION WHEN OTHERS THEN NULL;
END $$;

DO $$ BEGIN
  DROP FUNCTION IF EXISTS public.handle_new_user();
EXCEPTION WHEN OTHERS THEN NULL;
END $$;

DO $$ BEGIN DROP TABLE IF EXISTS "FeedComment" CASCADE; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN DROP TABLE IF EXISTS "FeedLike" CASCADE; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN DROP TABLE IF EXISTS "Review" CASCADE; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN DROP TABLE IF EXISTS "Challenge" CASCADE; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN DROP TABLE IF EXISTS "P2PLoan" CASCADE; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN DROP TABLE IF EXISTS "ProfileView" CASCADE; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN DROP TABLE IF EXISTS "Notification" CASCADE; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN DROP TABLE IF EXISTS "Proposal" CASCADE; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN DROP TABLE IF EXISTS "Order" CASCADE; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN DROP TABLE IF EXISTS "Demand" CASCADE; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN DROP TABLE IF EXISTS "Service" CASCADE; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN DROP TABLE IF EXISTS "Product" CASCADE; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN DROP TABLE IF EXISTS "Shop" CASCADE; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN DROP TABLE IF EXISTS "Transaction" CASCADE; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN DROP TABLE IF EXISTS "MarketPrice" CASCADE; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN DROP TABLE IF EXISTS "Asset" CASCADE; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN DROP TABLE IF EXISTS "GameEvent" CASCADE; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN DROP TABLE IF EXISTS "ProjectExpense" CASCADE; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN DROP TABLE IF EXISTS "Project" CASCADE; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN DROP TABLE IF EXISTS "Loan" CASCADE; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN DROP TABLE IF EXISTS "GameSettings" CASCADE; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN DROP TABLE IF EXISTS "User" CASCADE; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN DROP TABLE IF EXISTS "Business" CASCADE; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN DROP TABLE IF EXISTS "agents" CASCADE; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN DROP TABLE IF EXISTS "loans" CASCADE; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN DROP TABLE IF EXISTS "transactions" CASCADE; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN DROP TABLE IF EXISTS "posts" CASCADE; EXCEPTION WHEN OTHERS THEN NULL; END $$;

-- Vérifier qu'il ne reste rien
SELECT tablename FROM pg_tables WHERE schemaname = 'public';
